### PR TITLE
Split socket code from OTA into extra componnent

### PR DESCRIPTION
**Pull request by angelnu**
Draft to split the socket usage from the OTA component.

Usage:

```yaml
ota:
  password: bla
  unprotected_writes: True
ota_socket:
```

### CODE REVIEW

**Comment by oarcher** [comment]
Do you forgot to push some commits ?

I had to do some minor fixes to your code to be able to run it:
```
diff --git a/esphome/components/ota_socket/ota_frontend_socket.cpp b/esphome/components/ota_socket/ota_frontend_socket.cpp
index bbbcd1c7..a6f16a14 100644
--- a/esphome/components/ota_socket/ota_frontend_socket.cpp
+++ b/esphome/components/ota_socket/ota_frontend_socket.cpp
@@ -93,12 +93,12 @@ void OTAFrontendSocket::handle_() {
   }
 
   ESP_LOGD(TAG, "Starting OTA Update from %s...", this->client_->getpeername().c_str());
-  ota::global_ota_component->do_OTA_session(this);
+  ota::global_ota_component->do_ota_session(this);
 }
 
 ssize_t OTAFrontendSocket::read(uint8_t *buf, size_t len) { return this->client_->read(buf, len); }
 ssize_t OTAFrontendSocket::write(const uint8_t *buf, size_t len) { return this->client_->write(buf, len); }
-void OTAFrontendSocket::closeSession() {
+void OTAFrontendSocket::close_session() {
   this->client_->close();
   this->client_ = nullptr;
 }
diff --git a/esphome/components/ota_socket/ota_frontend_socket.h b/esphome/components/ota_socket/ota_frontend_socket.h
index c380583f..9a9425fc 100644
--- a/esphome/components/ota_socket/ota_frontend_socket.h
+++ b/esphome/components/ota_socket/ota_frontend_socket.h
@@ -17,7 +17,7 @@ class OTAFrontendSocket : public Component, public ota::OTAFrontend {
 
   ssize_t read(uint8_t *buf, size_t len) override;
   ssize_t write(const uint8_t *buf, size_t len) override;
-  void closeSession() override;
+  void close_session() override;
 
   // ========== INTERNAL METHODS ==========
   // (In most use cases you won't need these)
```

Then I had this error message:
`ERROR Error binary size: Error: The OTA partition on the ESP is too small. ESPHome needs to resize this partition, please flash over USB.`

So I've flashed over usb as requested, and `ota_socket` works!

**Comment by oarcher** [comment]
For implementing `ota_http` component using this new `ota` base component, I was thinking to implement virtual methods from `OTAFrontend`.

 And then from my flash action (`  OTAFrontendHttp::flash`,  so `this` is the http frontend):
  - `this->init_session()`  to connect to http://example.com/firmware.bin with `http GET` method.
  - call `ota::global_ota_component->do_ota_session(this);`

But then, in https://github.com/angelnu/esphome-1/blob/bbbf34096fdb8186343866ec846607db13ab994e/esphome/components/ota/ota_component.cpp#L82

There is a bi-directional communication protocol (magick test, reply with version, ask for features...) that can't be implemented with a simple `http GET`:  By calling `frontend->read(buf, size)` , we simply get `size` bytes from the `firmware.bin` file.

**Comment by angelnu** [comment]
@oarcher - if it is not possible to implement a bi-directional communication (example, using http sockets) then we have two options:
- keep the backend as the common code as it does not make any assumptions on how the frontend works
- implement a OTA_component class with different methods for the functions exposed by the OTA backend + getting the features + the reboot:
  - get features - so you know if compression is supported, writing partitions, reading partitions, etc
  - write_partition(frontend with read virtual function, bool do_restart)
  - read_partition(frontend with write virtual function, bool do_restart)
  - upgrade_firmware(frontend with read virtual function, bool do_restart)

The second IMO would be cleaner but requires more refactoring of the OTAcomponent. If we agree on the APIs I could give a try with a different PR and drop this one.

**Comment by oarcher** [comment]
@angelnu 

Yes, I agree with you about the 2nd option: if `ota` give some helpers function, it will be easiest to implement different protocols, with full `ota` backend functionalities.

As a first glance, I'm ok with your API proposal, but unfortunately, I don't have many time to work on this now. Hopefully mid-january...

So perhaps we can work on this after https://github.com/esphome/esphome/pull/5535 and https://github.com/esphome/esphome/pull/5586 as been merged ? (In this order, has your PR#5535 will break mine, but with only minor fixes on my side (https://github.com/esphome/esphome/pull/5586#issuecomment-1776048466)

**Pull request closed without merging**
